name: ci

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'README.md'

concurrency:
  # Taken from scalameta/metals
  # On main, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  group: ${{ (github.ref == 'refs/heads/main' ||  startsWith(github.ref, 'refs/tags') ) && format('contributor-pr-base-{0}', github.sha) || format('contributor-pr-{0}', github.ref) }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Check formatting
      run: 
        ./mill -i __.checkFormat
    - name: Check scalafix
      run: 
        ./mill -i __.fix --check

  test:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '17']

    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Compile
      run:
        ./mill -i __.compile

    - name: Test
      run:
        ./mill -i --debug itest[_].test
